### ISSUE TITLE
Finish Entire checklist 

### ISSUE THREAD

**Issue by jwithington** [jwithington/gatsby-theme-hardlikealgebra#5]
## Submission Checklist

To ensure your Theme Jam submission [follows the rules](https://themejam.gatsbyjs.org/rules), use this checklist:

- [ ] Use our [accessibility guide][a11y] to ensure your site meets our accessibility standards
- [ ] Run a performance audit using [Lighthouse][] and/or [WebPageTest][]
- [ ] Set up a live demo using [Netlify][] or [GitHub Pages][]
- [ ] Add installation documentation to the README
- [x] Update the `name` field in `package.json`
- [x] Update the `author` field in `package.json`
- [x] Update the `repository` field in `package.json`
- [x] Make sure the theme’s `keywords` in `package.json` include `gatsby`, `gatsby-theme`, and `gatsby-plugin`
- [ ] Publish your theme to npm ([docs][npmpublish])
- [ ] Submit your theme at https://themejam.gatsbyjs.org
